sudo: required
services:
  - docker

before_install:
  - docker build -t kavianba/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kavianba/react-test npm run test -- --coverage

after_success: 
  - docker build -t kavianba/multi-client ./client
  - docker build -t kavianba/multi-nginx ./nginx
  - docker build -t kavianba/multi-server ./server
  - docker build -t kavianba/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kavianba/multi-client
  - docker push kavianba/multi-nginx
  - docker push kavianba/multi-server
  - docker push kavianba/multi-worker


